name = "minifeed"
compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "minifeed"
database_id = "d059129a-d855-4e39-ae1f-64e92b9c40a1"
# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
