name = "minifeed"
compatibility_date = "2023-01-01"

workers_dev = false
route = { pattern = "minifeed.net", custom_domain = true }
main = "src/index.ts"

[vars]
TYPESENSE_API_KEY_SEARCH = "GCuPvjR4vz3gvACRo2N5hpRjZnEaijKE"
TYPESENSE_BLOG_FEEDS_COLLECTION = "blog_feeds"
TYPESENSE_CLUSTER = "3afyidm6tgzxlvq7p-1.a1.typesense.net"
TYPESENSE_ITEMS_COLLECTION = "items"

[site]
bucket = "./assets"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "minifeed"
database_id = "d059129a-d855-4e39-ae1f-64e92b9c40a1"

[[queues.producers]]
queue = "feed-update"
binding = "FEED_UPDATE_QUEUE"

[[queues.consumers]]
queue = "feed-update"
max_batch_size = 1 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[triggers]
crons = [ "*/30 * * * *" ]
