name: Tag Release

on:
  push:
    paths:
      - 'src/changelog.ts'

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          chmod +x create_tag.sh
          ./create_tag.sh
        working-directory: ${{ github.workspace }}
